[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mypy_baseline"
authors = [{ name = "Gram", email = "git@orsinium.dev" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["version", "description"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Typing :: Typed",
]
keywords = ["mypy", "baseline", "typing", "annotations", "type annotations"]
dependencies = []

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "requests", "responses"]
lint = ["flake8", "isort", "mypy", "types-requests", "types-toml", "unify"]
docs = ["sphinx", "myst-parser"]


[project.urls]
Source = "https://github.com/orsinium-labs/mypy-baseline"

[project.scripts]
mypy-baseline = "mypy_baseline:entrypoint"

[tool.mypy]
files = ["mypy_baseline", "tests"]
python_version = "3.8"
ignore_missing_imports = true
# follow_imports = "silent"
show_error_codes = true
check_untyped_defs = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.isort]
profile = "django"
lines_after_imports = 2
skip = ".venvs/"

[tool.pytest.ini_options]
addopts = [
    "--cov=mypy_baseline",
    "--cov-report=html",
    "--cov-report=term-missing:skip-covered",
    "--cov-fail-under=80",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING",
    "    pass",
    "except ImportError:",
]

[tool.coverage.run]
branch = true
